[2020-06-10 19:17:46,564] INFO in views: Logged out user admin
[2020-06-10 19:18:00,168] INFO in views: Logged in user admin
[2020-06-10 19:18:19,269] INFO in views: User admin created new application - test
[2020-06-10 19:18:47,866] INFO in views: User admin added new device dev1 test for application 0513d8d9
[2020-06-10 19:19:21,955] INFO in views: User admin created alert 7d6c9e - dev1 test.a > 0 for application 0513d8d9
[2020-06-10 19:19:32,734] INFO in views: User admin deleted alert 7d6c9e for application 0513d8d9
[2020-06-10 19:20:04,752] INFO in views: User admin created automation 14f87d - IF dev1 test.a > 0 THEN dev1 test.confID_1 = 1 for application 0513d8d9
[2020-06-10 19:20:12,716] INFO in views: User admin deleted automation 14f87d for application 0513d8d9
[2020-06-10 19:20:35,490] INFO in views: User admin deleted device 1 for application 0513d8d9
[2020-06-10 19:22:26,286] INFO in views: User admin deleted config messsage AQIxAA== for application 0513d8d9 device 1
[2020-06-10 19:26:21,369] INFO in views: User admin downloaded data for application 0513d8d9 device 1
[2020-06-10 19:26:44,083] INFO in views: User admin deleted for application 0513d8d9 device 1
[2020-06-10 19:26:58,457] INFO in views: User admin deleted application - 0513d8d9
[2020-06-11 09:29:26,446] WARNING in views_admin: Administrator admin created new user lolo
[2020-06-11 09:39:23,858] WARNING in views_admin: Administrator admin created new user lolo
[2020-06-11 09:39:39,600] WARNING in views_admin: Administrator admin deleted user lolo
[2020-06-11 09:40:02,339] WARNING in views_admin: Administrator admin created new application 598bee34 for user-user
[2020-06-11 09:40:34,846] ERROR in views_admin: Administrator admin failed to add device application e38dc490 for user-user - INSERT has more expressions than target columns
LINE 5:         ('asd', '1', 'asd', '\x7b226d6f64656c223a20226a736f6...
                                    ^

[2020-06-11 09:41:26,391] ERROR in views_admin: Administrator admin failed to add device application e38dc490 for user-user - INSERT has more expressions than target columns
LINE 5:         ('dev1 test', '1', 'dsds', '\x7b226d6f64656c223a2022...
                                           ^

[2020-06-11 09:50:18,424] WARNING in views_admin: Administrator admin created new application 5e4932cc for user-user
[2020-06-11 09:50:36,442] WARNING in views_admin: Administrator admin added new device 1 application 5e4932cc for user-user
[2020-06-11 09:50:59,309] WARNING in views_admin: Administrator admin created alert 7d7a6d for application 5e4932cc for user-user
[2020-06-11 09:53:15,478] WARNING in views_admin: Administrator admin created alert 8b867b for application 5e4932cc for user-user
[2020-06-11 09:53:19,487] WARNING in views_admin: Administrator admin deleted alert 8b867b for application 5e4932cc for user-user
[2020-06-11 09:53:52,334] WARNING in views_admin: Administrator admin created automation 72249b for application 5e4932cc for user-user
[2020-06-11 09:54:00,999] WARNING in views_admin: Administrator admin deleted automation 72249b for application 5e4932cc for user-user
[2020-06-11 09:54:21,228] WARNING in views_admin: Administrator admin changed settings for application 5e4932cc for user-user
[2020-06-11 09:54:28,518] WARNING in views_admin: Administrator admin deleted application 5e4932cc for user-user
[2020-06-11 09:55:16,026] INFO in views: User admin created new application - test
[2020-06-11 10:01:02,029] INFO in views: User admin deleted application - 649fd3ab
[2020-06-30 10:56:32,460] INFO in views: Logged in superuser admin
[2020-06-30 10:57:05,008] INFO in views: Logged in superuser admin
[2020-06-30 12:36:13,017] ERROR in views: superuser admin failed to create alert for application 3b56f3d8 - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
[2020-06-30 12:38:40,214] ERROR in views: superuser admin failed to create alert for application 3b56f3d8 - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
[2020-06-30 12:40:31,061] ERROR in views: superuser admin failed to create alert for application 3b56f3d8 - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
[2020-06-30 12:41:36,826] ERROR in views: superuser admin failed to create alert for application 3b56f3d8 - 'alert'
[2020-06-30 13:05:01,368] ERROR in views: superuser admin failed to create alert for application 3b56f3d8 - Exception: 'alert'
[2020-06-30 13:06:54,240] INFO in views: superuser admin created alert 884e51 - ddmjson.temperature > 0 for application 3b56f3d8
[2020-06-30 14:27:24,473] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 1, in top-level template code
    {% extends 'logged_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 1, in top-level template code
    {% extends 'general_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/general_layout.html", line 35, in top-level template code
    {% block content %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 196, in block "content"
    {% block body %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 36, in block "body"
    {% for a in alert_list %}
TypeError: 'IndexError' object is not iterable
[2020-06-30 14:27:58,458] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 1, in top-level template code
    {% extends 'logged_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 1, in top-level template code
    {% extends 'general_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/general_layout.html", line 35, in top-level template code
    {% block content %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 196, in block "content"
    {% block body %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 36, in block "body"
    {% for a in alert_list %}
TypeError: 'IndexError' object is not iterable
[2020-06-30 14:29:43,392] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 1, in top-level template code
    {% extends 'logged_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 1, in top-level template code
    {% extends 'general_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/general_layout.html", line 35, in top-level template code
    {% block content %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 196, in block "content"
    {% block body %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 36, in block "body"
    {% for a in alert_list %}
TypeError: 'IndexError' object is not iterable
[2020-06-30 14:36:01,025] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 1, in top-level template code
    {% extends 'logged_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 1, in top-level template code
    {% extends 'general_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/general_layout.html", line 35, in top-level template code
    {% block content %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 196, in block "content"
    {% block body %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 36, in block "body"
    {% for a in alert_list %}
TypeError: 'IndexError' object is not iterable
[2020-06-30 14:36:08,046] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 1, in top-level template code
    {% extends 'logged_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 1, in top-level template code
    {% extends 'general_layout.html' %}
  File "/home/pi/thso.server/app/app/templates/general_layout.html", line 35, in top-level template code
    {% block content %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/logged_layout.html", line 196, in block "content"
    {% block body %} {% endblock %}
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 36, in block "body"
    {% for a in alert_list %}
TypeError: 'IndexError' object is not iterable
[2020-06-30 16:52:38,747] INFO in views: superuser admin deleted alert 884e51 for application 3b56f3d8
[2020-06-30 16:52:41,086] INFO in views: superuser admin deleted alert 7201c2 for application 3b56f3d8
[2020-06-30 17:02:58,029] ERROR in app: Exception on /application/3b56f3d8/device/1/download-csv [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 332, in application_device_download_csv
    f.write(str(row[2][v]))
TypeError: memoryview: invalid slice key
[2020-06-30 17:10:07,673] ERROR in app: Exception on /recent-activity [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/views.py", line 366, in recent_activity
    ra += '<tr><th scope="row">'+r[1]+'</th><th>'+r[2]+'</th><th>'+r[0]+'</th><th>'+str(ddm.read_data(r[3], dev[3]))+'</th></tr>'
  File "./app/helpers/device_data_model.py", line 147, in read_data
    return json.loads(data.decode('utf-8'))
AttributeError: 'memoryview' object has no attribute 'decode'
[2020-06-30 17:17:18,567] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 41, in template
    <th> {{ a[5]|split('_')[1] }} </th>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['
[2020-06-30 17:17:44,630] ERROR in app: Exception on /application/3b56f3d8/alerts [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/helpers/decorators.py", line 35, in protected_function
    return f(*args, **kwargs)
  File "./app/views.py", line 495, in application_alerts
    return render_template('new/public/alerts.html', alert_list=alerts[1], app=ap[1])
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/thso.server/app/app/templates/new/public/alerts.html", line 41, in template
    <th> {{ a[5]|split('_')[1] }} </th>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '['
[2020-06-30 17:18:31,111] INFO in views: superuser admin created alert 8bbd83 - devmpack.lever == 1 for application 3b56f3d8
[2020-06-30 17:19:11,846] INFO in views: superuser admin created alert ddb142 - ddmjson.lever == 0 for application 3b56f3d8
[2020-06-30 17:41:15,560] ERROR in app: Exception on /administration/admin/recent-activity [GET]
Traceback (most recent call last):
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/thso.server/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/helpers/decorators.py", line 23, in restricted_function
    return f(*args, **kwargs)
  File "./app/views_admin.py", line 518, in administration_user_recent_activity
    ra += '<tr><th scope="row">'+r[1]+'</th><th>'+r[2]+'</th><th>'+r[0]+'</th><th>'+str(ddm.read_data(r[3], dev[3]))+'</th></tr>'
  File "./app/helpers/device_data_model.py", line 147, in read_data
    return json.loads(data.decode('utf-8'))
AttributeError: 'memoryview' object has no attribute 'decode'
[2020-06-30 17:44:34,584] WARNING in views_admin: Administrator admin created alert 7ab5c9 for application 3b56f3d8 for admin
[2020-06-30 17:52:07,946] WARNING in views_admin: Administrator admin created alert 3235b2 for application 3b56f3d8 for admin
[2020-06-30 17:52:27,874] WARNING in views_admin: Administrator admin deleted alert 3235b2 for application 3b56f3d8 for admin
